#!/usr/bin/env node
/**
 * vectorize.js  — two-colour vectorizer
 * ─────────────────────────────────────────────────────────────────
 * Produces a two-layer SVG using two greyscale thresholds:
 *   Layer 1 (behind, soft blur): light pink  (#C4698A) — all coloured areas
 *   Layer 2 (front, crisp):      dark maroon (#8B1538) — darkest areas only
 *
 * Both layers use the same greyscale pipeline as the original single-colour
 * script, so curves are smooth. The pink layer threshold is higher so it
 * catches the lighter petal fills; dark sits on top covering its own region.
 *
 * USAGE
 *   node scripts/vectorize.js <input.jpg|png> [output.svg]
 * ─────────────────────────────────────────────────────────────────
 */

const path = require('path');
const fs   = require('fs');

function requireOrExit(pkg) {
  try { return require(pkg); }
  catch {
    console.error(`\n  Missing package: ${pkg}`);
    console.error(`  Run:  npm install --save-dev potrace jimp\n`);
    process.exit(1);
  }
}
const potrace = requireOrExit('potrace');
const Jimp    = requireOrExit('jimp');

// ── args ────────────────────────────────────────────────────────
const inputFile = process.argv[2];
if (!inputFile) {
  console.log('\nUsage: node scripts/vectorize.js <logo.jpg> [output.svg]\n');
  process.exit(0);
}
if (!fs.existsSync(inputFile)) {
  console.error(`\nFile not found: ${inputFile}\n`);
  process.exit(1);
}

const outputFile = process.argv[3]
  || path.join(
      path.dirname(inputFile),
      path.basename(inputFile, path.extname(inputFile)) + '-vector.svg'
     );

console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('  Ru Shakti Logo Vectorizer  (two-colour)');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log(`  Input:  ${inputFile}`);
console.log(`  Output: ${outputFile}`);
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

// ── shared greyscale prep ────────────────────────────────────────
// Returns a contrast-boosted greyscale Jimp image ready for thresholding.
function prepareGreyscale(img) {
  return img.clone().contrast(0.3).greyscale();
}

// ── wrap potrace.trace in a Promise, return the <path …/> element ─
function traceBuf(buf, color, threshold, turdSize) {
  return new Promise((resolve, reject) => {
    potrace.trace(buf, {
      threshold,
      turdSize,
      alphaMax:     1.3,
      optCurve:     true,
      optTolerance: 0.4,
      color,
      background: 'transparent',
    }, (err, svg) => {
      if (err) return reject(err);
      const m = svg.match(/<path[\s\S]*?\/>/);
      resolve(m ? m[0] : '');
    });
  });
}

// ── main ────────────────────────────────────────────────────────
Jimp.read(inputFile)
  .then(img => {
    const w = img.getWidth();
    const h = img.getHeight();
    console.log(`  Image size: ${w} × ${h}`);
    console.log('  Preparing greyscale layers...');

    const grey = prepareGreyscale(img);

    // Dark layer: only pixels darker than 160 (the solid maroon strokes/fills)
    const darkImg = grey.clone().threshold({ max: 160 });

    // Pink layer: anything darker than 210 — catches the lighter petal fills too.
    // Threshold is passed to potrace directly (not pre-binarised) so potrace
    // decides the cut, giving the same smooth edge quality as the original script.
    const pinkImg = grey.clone();

    const toBuffer = jimpImg =>
      new Promise((res, rej) =>
        jimpImg.getBuffer(Jimp.MIME_PNG, (err, buf) =>
          err ? rej(err) : res(buf)
        )
      );

    return Promise.all([
      toBuffer(darkImg),
      toBuffer(pinkImg),
      Promise.resolve({ w, h }),
    ]);
  })
  .then(([darkBuf, pinkBuf, { w, h }]) => {
    console.log('  Tracing dark maroon layer  (threshold 160)...');
    // Dark layer: pre-binarised at 160, so pass 128 to potrace
    const p1 = traceBuf(darkBuf, '#8B1538', 128, 2);

    console.log('  Tracing light pink layer   (threshold 210)...');
    // Pink layer: let potrace threshold at 210 on the greyscale image
    // turdSize=6 drops compression-noise specks but keeps lotus shapes
    const p2 = traceBuf(pinkBuf, '#C4698A', 210, 6);

    return Promise.all([p1, p2, Promise.resolve({ w, h })]);
  })
  .then(([darkPath, pinkPath, { w, h }]) => {
    const svg = `<!-- Generated by vectorize.js (two-colour, dual-threshold)
     Pink layer (#C4698A, threshold 210, blurred) — all coloured areas
     Dark layer (#8B1538, threshold 160, crisp)   — darkest strokes/fills -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}">
  <defs>
  </defs>

  <!-- ① light pink — all coloured areas (behind, no glow) -->
  <g>
    ${pinkPath.replace(/fill="[^"]*"/, 'fill="#C4698A"')}
  </g>

  <!-- ② dark maroon — darkest strokes and fills (front, crisp) -->
  ${darkPath.replace(/fill="[^"]*"/, 'fill="#8B1538"')}
</svg>`;

    fs.writeFileSync(outputFile, svg, 'utf8');

    console.log('\n  ✓ Done!\n');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('  Two-colour SVG written to:', outputFile);
    console.log('\n  Tune thresholds if needed:');
    console.log('    Dark layer  → traceBuf(..., 128, ...)  lower = less dark area');
    console.log('    Pink layer  → traceBuf(..., 210, ...)  lower = less pink area');
    console.log('    Blur amount → stdDeviation="8" in the SVG <filter>');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  })
  .catch(err => {
    console.error('\n  Error:', err.message);
    process.exit(1);
  });
